branches:
  # As AppVeyor test is slow, we only run AppVeyor against development and
  # stable branches.
  # To disable AppVeyor against Pull-Requests, disable Pull-Request event
  # in web-hook configuration of GitHub settings.
  only:
    - master
    - v2
    - appveyor

environment:
  global:
    # SDK v7.0 MSVC Express 2008's SetEnv.cmd script will fail if the
    # /E:ON and /V:ON options are not enabled in the batch script intepreter
    # See: https://stackoverflow.com/a/13751649/163740
    CMD_IN_ENV: "cmd /E:ON /V:ON /C .\\appveyor\\run_with_env.cmd"

  matrix:

    # Pre-installed Python versions, which Appveyor may upgrade to
    # a later point release.
    # See: https://www.appveyor.com/docs/installed-software#python

    - PYTHON: "C:\\Miniconda-x64"
      PYTHON_VERSION: "2.7.x"
      PYTHON_ARCH: "64"

    - PYTHON: "C:\\Miniconda35-x64"
      PYTHON_VERSION: "3.5.x"
      PYTHON_ARCH: "64"

install:
  - ECHO "Filesystem root:"
  - ps: "ls \"C:/\""

  - ECHO "Installed SDKs:"
  - ps: "ls \"C:/Program Files/Microsoft SDKs/Windows\""

  # Install Python (from the official .msi of https://www.python.org) and pip when
  # not already installed.
  - ps: if (-not(Test-Path($env:PYTHON))) { & appveyor\install.ps1 }

  # Install CUDA.
  - ps: appveyor\install-cuda.ps1
  - "SET CUDA_PATH=%ProgramFiles%\\NVIDIA GPU Computing Toolkit\\CUDA\\v9.1"
  - "SET NVTOOLSEXT_PATH=%ProgramFiles%\\NVIDIA Corporation\\NvToolsExt"
  - "SET PATH=%CUDA_PATH%\\bin;%NVTOOLSEXT_PATH%\\bin\\x64;%PATH%"

  # Workaround the issue that `stdint.h` is missing on Visual Studio 9.0, which is used by Python 2.7.
  # AppVeyor environment has Visual Studio 10.0, which comes with `stdint.h`.
  - copy "%ProgramFiles%\\Microsoft Visual Studio 10.0\\VC\\include\\stdint.h" "%ProgramFiles%\\Microsoft Visual Studio 9.0\\VC\\include\\stdint.h"

  # Prepend newly installed Python to the PATH of this build (this cannot be
  # done from inside the powershell script as it would require to restart
  # the parent CMD process).
  - "SET PATH=%PYTHON%;%PYTHON%\\Scripts;%PATH%"

  # Check that we have the expected version and architecture for Python
  - "python --version"
  - "python -c \"import struct; print(struct.calcsize('P') * 8)\""

  - "conda install -y -q setuptools"
  - "conda update -y -q pip"
  - "pip install Cython"

build_script:
  # Build the compiled extension
  - "%CMD_IN_ENV% python setup.py build install -vvvv"

test_script:
  # Installation test
  - "%CMD_IN_ENV% pip install -U -e ."
