configs {
  key: "cupy-unit-linux-cuda102"
  value {
    requirement {
      cpu: 8
      memory: 24
      disk: 10
      gpu: 2
    }
    time_limit {
      seconds: 1800
    }
    checkout_strategy {
      include_dot_git: true
    }
    environment_variables { key: "GPU" value: "2" }
    command: "echo v8 branch"
  }
}
