name: "FlexCI"

on:
  push:
    branches: ["master", "v[0-9]+", "dispatch-push-event-from-actions"]
  issue_comment:
    types: [created]

jobs:
  dispatch:
    if: |
        github.repository_owner == 'kmaehashi' &&
        (
            (github.event_name == 'issue_comment' &&
             github.event.issue.pull_request &&
             contains(github.event.comment.body, '/test ')) ||
            (github.event_name == 'push')
        )
    runs-on: ubuntu-20.04

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'

    - name: Setup Environment
      run: |
        pip install pygithub

    - name: Dispatch
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        FLEXCI_WEBHOOK_SECRET: ${{ secrets.FLEXCI_WEBHOOK_SECRET }}
      run: |
        cat "${GITHUB_EVENT_PATH}"
        ./.github/workflows/flexci_dispatcher.py \
            --event "${GITHUB_EVENT_NAME}" \
            --webhook "${GITHUB_EVENT_PATH}" \
            --projects ./.pfnci/config.tags.json
