name: "Wheel Build"

on:
  workflow_dispatch:
    inputs:
      release:
        description: 'Drafted Release to Upload'
        type: string

jobs:
  wheel-linux:
    if: |
        github.repository_owner == 'kmaehashi'
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        #cuda: ["10.2", "10.2-jetson", "11.0", "11.1", "11.2", "11.3", "11.4", "11.5"]
        cuda: ["10.2", "11.0", "11.1", "11.2", "11.3", "11.4", "11.5"]
    env:
      TARGET_BRANCH: "master" # ${{ github.ref_name }}

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'

    - name: Build (${{ matrix.cuda }})
      run: |
        git clone --branch "${TARGET_BRANCH}" https://github.com/cupy/cupy-release-tools.git
        cd cupy-release-tools
        CUPY_RELEASE_SKIP_VERIFY=1 ./.pfnci/wheel-linux/main.sh "${{ matrix.cuda }}" "3.7,3.8,3.9,3.10" "${TARGET_BRANCH}"

    - name: Upload
      if: ${{ github.event.inputs.release }} != ""
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        cd cupy-release-tools
        gh release --repo kmaehashi/cupy upload "${{ github.event.inputs.release }}" *.whl
